development:
  adapter: postgresql
  database: mariomakerreview_production
  username: Ricky
  password:
  encoding: utf8
  pool: 5

test: &test
  adapter: postgresql
  database: mariomakerreview_production
  username: Ricky
  password:
  encoding: utf8
  pool: 5

cucumber:
  <<: *test

production:
  adapter: postgresql
  encoding: unicode
  database: mariomakerreview_production
  pool: 5
